version: "3"
services:
  grafana:
    image: grafana/grafana:8.3.4
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "boazreicher-mosaicplot-panel"
      GF_INSTALL_PLUGINS: https://github.com/boazreicher/mosaic-plot/releases/download/v1.0.1/boazreicher-mosaicplot-panel-1.0.1.zip;boazreicher-mosaicplot-panel
    volumes:
      - ./provisioning:/etc/grafana/provisioning

      
